global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
  - "nexent_alerts.yml"

scrape_configs:
  # Nexent Backend - LLM Metrics
  - job_name: 'nexent-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Adjust based on your backend service
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Jaeger Metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093
