name: Run Automated Tests

on:
  workflow_dispatch:
    inputs:
      runner_label_json:
        description: 'JSON 格式的 runner 标签数组'
        required: true
        default: '["self-hosted", "X64", "Linux", "aliyun-154"]'

jobs:
  test:
    runs-on: ${{ fromJson(inputs.runner_label_json) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install pytest selenium -i https://pypi.mirrors.ustc.edu.cn/simple/

      - name: Create test results directory
        run: mkdir -p test-results

      - name: Run Selenium tests with pytest
        run: |
          python3 -m pytest test/web_test/web_test.py --maxfail=1 --disable-warnings -v --junitxml=test-results/pytest-report.xml

      - name: Upload pytest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: test-results/pytest-report.xml

      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'test-results/pytest-report.xml'