name: Run Automated Unit Tests

on:
  workflow_dispatch:
    inputs:
      runner_label_json:
        description: 'JSON格式的runner标签数组（如["ubuntu-latest"]或["self-hosted"])'
        required: false
        default: '["ubuntu-latest"]'
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ${{ github.event_name == 'workflow_dispatch' && fromJson(github.event.inputs.runner_label_json) || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install coverage
        run: pip install coverage

      - name: Install dependencies
        run: pip install pytest

      - name: Run all tests and collect coverage
        run: |
          coverage run -m pytest test/backend/test_sample.py
          coverage report --show-missing
          coverage xml
          echo "*** Coverage Summary ***"
          coverage report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
          directory: .