name: Run Automated Unit Tests

on:
  workflow_dispatch:
    inputs:
      runner_label_json:
        description: 'JSON格式的runner标签数组（如["ubuntu-latest"]或["self-hosted"])'
        required: false
        default: '["ubuntu-latest"]'
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ${{ github.event_name == 'workflow_dispatch' && fromJson(github.event.inputs.runner_label_json) || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'

      - name: Install coverage
        run: pip install coverage -i https://pypi.mirrors.ustc.edu.cn/simple/

      - name: Run all tests and collect coverage
        run: |
          coverage run --branch -m unittest test/backend/test_sample.py
          coverage xml -o test/backend/coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: test/backend/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}