name: Docker Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build test'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - main
          - data-process

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build main application image
        if: ${{ github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'main' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./make/main/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          tags: nexent/nexent:latest

      - name: Build data process image
        if: ${{ github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'data-process' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./make/dataprocess/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          tags: nexent/nexent-data-process:latest 