name: Docker Build All Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build base image
        run: docker build --progress=plain -t nexent/nexent-base -f make/base/Dockerfile .

      - name: Build main application image
        run: docker build --progress=plain -t nexent/nexent -f make/main/Dockerfile .

      - name: Build data process image
        run: docker build --progress=plain -t nexent/nexent-data-process -f make/data_process/Dockerfile .

      - name: Build web frontend image
        run: docker build --progress=plain -t nexent/nexent-web -f make/web/Dockerfile . 